name: Testing Actions Workflow

on: 
  push:
    branches: [main]
  pull_request: 
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
    - name: Run echo command
      run: echo "Hello world"
